server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: "SetiFranquicias"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:franquicias_db}}
    username: ${SPRING_R2DBC_USERNAME:${DB_USERNAME:postgres}}
    password: ${SPRING_R2DBC_PASSWORD:${DB_PASSWORD:postgres}}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    root: INFO
    ms.seti: DEBUG
    org.springframework.r2dbc.connection: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"
